[package]
name = "mvn-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
nom_locate = "4.0.0"
num-traits = "0.2.15"

[dev-dependencies]
pretty_assertions = "1.2.1"
